export const todoCardStyles = {
    wrapper: 'bg-white rounded-lg shadow-sm hover:shadow-md transition-shadow p-6',
    contentWrapper: 'flex items-start justify-between gap-4',
    mainContent: 'flex-1',
    title: 'text-lg font-semibold text-gray-900 mb-2',
    details: 'text-gray-600 text-sm mb-4 whitespace-pre-wrap',
    statusWrapper: 'flex items-center gap-2',
    statusBadge: 'inline-flex items-center px-3 py-1 rounded-full text-sm',
    statusIcon: 'w-4 h-4 mr-1',
    actionsWrapper: 'flex items-center gap-2',
    select: 'px-3 py-1.5 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500',
    deleteButton: 'p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors',
    deleteIcon: 'w-4 h-4',
    statusWrapper: 'flex items-center gap-2',
};
